# Generated by Django 4.0.5 on 2022-06-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePagePictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Homepage name1')),
                ('img', models.ImageField(upload_to='media', verbose_name='Homepage img')),
                ('price', models.CharField(max_length=30, verbose_name='Homepage name2')),
            ],
            options={
                'verbose_name': 'HomePagePicture',
                'verbose_name_plural': 'HomePagePictures',
            },
        ),
    ]
