# Generated by Django 4.0.5 on 2022-06-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_homepagepictures'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageCategory1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='HomePageCategory1 name')),
                ('img', models.ImageField(upload_to='media', verbose_name='HomePageCategory1 img')),
                ('price', models.CharField(max_length=30, verbose_name='HomePageCategory1 price')),
            ],
            options={
                'verbose_name': 'HomePage1Category',
                'verbose_name_plural': 'HomePage1Categores',
            },
        ),
        migrations.CreateModel(
            name='HomePageCategory2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='HomePageCategory2 name')),
                ('img', models.ImageField(upload_to='media', verbose_name='HomePageCategory2 img')),
                ('price', models.CharField(max_length=30, verbose_name='HomePageCategory2 price')),
            ],
            options={
                'verbose_name': 'HomePage2Category',
                'verbose_name_plural': 'HomePage2Categores',
            },
        ),
        migrations.CreateModel(
            name='HomePageCategory3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='HomePageCategory3 name')),
                ('img', models.ImageField(upload_to='media', verbose_name='HomePageCategory3 img')),
                ('price', models.CharField(max_length=30, verbose_name='HomePageCategory3 price')),
            ],
            options={
                'verbose_name': 'HomePage3Category',
                'verbose_name_plural': 'HomePage3Categores',
            },
        ),
        migrations.CreateModel(
            name='HomePageCategory4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='HomePageCategory4 name')),
                ('img', models.ImageField(upload_to='media', verbose_name='HomePageCategory4 img')),
                ('price', models.CharField(max_length=30, verbose_name='HomePageCategory4 price')),
            ],
            options={
                'verbose_name': 'HomePage4Category',
                'verbose_name_plural': 'HomePage4Categores',
            },
        ),
        migrations.CreateModel(
            name='HomePageCategory5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='HomePageCategory5 name')),
                ('img', models.ImageField(upload_to='media', verbose_name='HomePageCategory5 img')),
                ('price', models.CharField(max_length=30, verbose_name='HomePageCategory5 price')),
            ],
            options={
                'verbose_name': 'HomePage5Category',
                'verbose_name_plural': 'HomePage5Categores',
            },
        ),
    ]
